#
# Playbook to simply apply the role to "all" hosts, that being in the case this is running as a test - the Vagrant host.
#
- hosts: all
  vars:
      ansible_pkg_mgr: apt
  roles:
    - williamyeh.oracle-java
  tasks:
    - include: 'tasks/main.yml'
  vars_files:
    - 'defaults/main.yml'